base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: true

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
